server:
  port: 7568
spring:
  application:
    name: calificaciones
  config:
    import: classpath:/mongo_secure.yml

info:
  app:
    name: mongo-service
    description: Gestion de servicios con mongo
    version: 1.0
